[package]
name = "palloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["spin", "allocator_api"]
allocator_api = []

[dependencies]
spin = { version = "0.9.2", optional = true }